### ISSUE TITLE
help us to get us back on track

### ISSUE THREAD

**Issue by wesleyvanneck** [ApolloBE/Apollo-Legacy#1]

**Comment by Wolfkid200444** [comment]
:}

**Comment by Fabiansigala** [comment]
More Devs needed

**Comment by therealdevs** [comment]
Aren't you all fake devs? All you do is copy and paste the stuff from pmmp right. Exposed

**Comment by therealdevs** [comment]
I know you've been effective in the past @Wesleyvanneeck @Wolfkid200444 @Fabiansigala

**Comment by wesleyvanneck** [comment]
@therealdevs this is why i did stop with fucking pmmp commintie

**Comment by wesleyvanneck** [comment]
@therealdevs hmm am realy a fake dev well think again look more at my profiel and am not hiding it you loser

**Comment by wesleyvanneck** [comment]
Close this shit
